export const TODO_LIST_REQUEST = "TODO_LIST_REQUEST";
export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS"
export const TODO_LIST_FAIL = "TODO_LIST_FAIL"
export const TODO_LIST_RESET = "TODO_LIST_RESET"

export const TODO_ADD_REQUEST = "TODO_ADD_REQUEST"
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS"
export const TODO_ADD_FAIL = "TODO_ADD_FAIL"
export const TODO_ADD_RESET = "TODO_ADD_RESET"

export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST"
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS"
export const TODO_DELETE_FAIL = "TODO_DELETE_FAIL"
export const TODO_DELETE_RESET = "TODO_DELETE_RESET"


export const TASK_ADD_REQUEST = "TASK_ADD_REQUEST"
export const TASK_ADD_SUCCESS = "TASK_ADD_SUCCESS"
export const TASK_ADD_FAIL = "TASK_ADD_FAIL"
export const TASK_ADD_RESET = "TASK_ADD_RESET"


export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST"
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS"
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL"
export const TASK_DELETE_RESET = "TASK_DELETE_RESET"